# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-14 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='main_app/default.png', upload_to='main_app/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restraunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('address_link', models.CharField(max_length=400)),
                ('website', models.URLField(max_length=264)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('phone', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='main_app')),
                ('map', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=15000)),
                ('short_desc', models.CharField(max_length=60)),
                ('average', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField()),
                ('restraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.Restraunt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
