# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-14 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restraunt',
            name='average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
