# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-18 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190615_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automotive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('address_link', models.CharField(max_length=400)),
                ('website', models.URLField(max_length=264)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('phone', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='main_app')),
                ('map', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=15000)),
                ('short_desc', models.CharField(max_length=60)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('address_link', models.CharField(max_length=400)),
                ('website', models.URLField(max_length=264)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('phone', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='main_app')),
                ('map', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=15000)),
                ('short_desc', models.CharField(max_length=60)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beauty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('address_link', models.CharField(max_length=400)),
                ('website', models.URLField(max_length=264)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('phone', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='main_app')),
                ('map', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=15000)),
                ('short_desc', models.CharField(max_length=60)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('address_link', models.CharField(max_length=400)),
                ('website', models.URLField(max_length=264)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('phone', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='main_app')),
                ('map', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=15000)),
                ('short_desc', models.CharField(max_length=60)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('address_link', models.CharField(max_length=400)),
                ('website', models.URLField(max_length=264)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('phone', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='main_app')),
                ('map', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=15000)),
                ('short_desc', models.CharField(max_length=60)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('address_link', models.CharField(max_length=400)),
                ('website', models.URLField(max_length=264)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('phone', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=264)),
                ('image', models.ImageField(upload_to='main_app')),
                ('map', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=15000)),
                ('short_desc', models.CharField(max_length=60)),
                ('average', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
