# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_automotive_bars_beauty_coffee_hotels_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='type',
            field=models.CharField(default='Restaurant', max_length=200),
            preserve_default=False,
        ),
    ]
