# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190628_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restraunt',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='restraunt',
            name='img3',
        ),
        migrations.AddField(
            model_name='restraunt',
            name='link1',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='link2',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='link3',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='link4',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='link5',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='average',
            field=models.IntegerField(blank=True, max_length=600, null=True),
        ),
    ]
