# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-04 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190628_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restraunt',
            name='closing_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restraunt',
            name='opening_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
