# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190704_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_list',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
